apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-java-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: hello-world-java
  template:
    metadata:
      labels:
        app: hello-world-java
    spec:
      containers:
      - name: hello-world-java
        image: aus-harborpd-01.bmc.com/shshirol-test-repo/hello-world-java:latest  
        ports:
        - containerPort: 8080  # Expose port if needed (depends on your app)

